"""Pixel to ground coordinates.

Converts detections from image pixels to projected coordinates, and writes georeferenced vector
output that opens directly in QGIS. Silent errors here produce plausible detections in the wrong
place, which is worse than a crash. Geometry-critical: covered by tests.

Detections arrive here already in scene coordinates: the tile-local step, and the reconciliation
of what overlapping tiles saw twice, are done by the time this module sees them. One transform
places the whole scene, so there is exactly one conversion and it happens here.
"""

from collections.abc import Sequence
from pathlib import Path

import geopandas as gpd

from darkvessel.data.scene import Scene
from darkvessel.detect.checkpoints import atomically
from darkvessel.detect.detector import PixelDetection

DETECTIONS_LAYER = "detections"


def to_ground(detections: Sequence[PixelDetection], scene: Scene) -> gpd.GeoDataFrame:
    """Place pixel detections on the ground, in the scene's CRS.

    A pixel index addresses the centre of that pixel, while an affine transform maps pixel
    *corners*; the half-pixel shift here is the difference between a detection reported at its
    centre and one reported half a pixel up and to the left.
    """
    corners = [(det.col + 0.5, det.row + 0.5) for det in detections]
    ground = [scene.transform * corner for corner in corners]

    return gpd.GeoDataFrame(
        {"score": [det.score for det in detections]},
        geometry=gpd.points_from_xy(
            [x for x, _ in ground],
            [y for _, y in ground],
        ),
        crs=scene.crs,
    )


def write_detections(detections: gpd.GeoDataFrame, path: Path) -> None:
    """Write detections as a GeoPackage layer, which QGIS opens without a conversion step.

    Written whole or not at all, through the same `atomically` the checkpoints use. This was an
    unlink followed by a write, which is fine while the only caller is `run` — a lost output is
    regenerated by running the chain again. `darkvessel context` is not that caller: it reads this
    file, samples the contextual layers at what it found, and writes the same path back, so the
    file being replaced is its own input. A write that failed halfway through would leave nothing
    to re-read and nothing to fall back on, and the way back would be the whole chain.
    """
    with atomically(path, keep_suffix=True) as partial:
        detections.to_file(partial, layer=DETECTIONS_LAYER, driver="GPKG")
